server {
    listen 80;
    listen [::]:80;

    server_name www.instepanavan.am;
    return 301 $scheme://instepanavan.am$request_uri;
}

server {
    listen 80;
    listen [::]:80;

    server_name instepanavan.am;

    client_max_body_size 100M;

    location ~ ^/api/ {
        proxy_pass    http://server:1337;
    }

    location ~ ^/uploads/ {
        proxy_pass    http://server:1337;
    }

    location ~ ^/image-proxy/(.+)$ {
        resolver      8.8.8.8 valid=300s;
        set $target   $1;
        proxy_pass    $target;
        proxy_hide_header Set-Cookie;
        proxy_ignore_headers Set-Cookie;
        add_header    Cache-Control "public, max-age=86400";
    }

    location / {
        proxy_pass    http://client:3000;
    }
}

server {
    listen 80;
    listen [::]:80;

    server_name api.instepanavan.am;

    client_max_body_size 100M;

    location / {
        proxy_pass    http://server:1337;
    }
}
